#ifndef ROTARY_ENCODER_H
#define ROTARY_ENCODER_H

#include "pico/stdlib.h"
#include "hardware/gpio.h"
#include "FreeRTOS.h"
#include "queue.h"

/**
 * @enum RotaryEventType
 * @brief Defines the types of events that can be generated by the rotary encoder.
 */
enum class RotaryEventType {
    ButtonPress,     ///< The rotary encoder button was pressed
    Clockwise,       ///< The rotary encoder was rotated clockwise
    CounterClockwise ///< The rotary encoder was rotated counter-clockwise
};

/**
 * @struct RotaryEvent
 * @brief Contains information about a rotary encoder event.
 *
 * This structure is used to pass events from the interrupt service routine
 * to the main application via a FreeRTOS queue.
 */
typedef struct {
    RotaryEventType type; ///< Type of event that occurred
    TickType_t time;      ///< FreeRTOS tick count when the event occurred
} RotaryEvent;

/**
 * @class RotaryEncoder
 * @brief A class for handling rotary encoder input with debouncing and event queuing.
 *
 * This class provides a simple interface for reading rotary encoder inputs
 * with built-in debouncing logic. It uses FreeRTOS queues to pass events
 * from interrupt context to task context.
 *
 * Features:
 *   - Handles rotary encoder rotation detection (clockwise/counter-clockwise)
 *   - Handles button press detection with debouncing
 *   - Uses FreeRTOS queues for thread-safe event passing
 *   - Configurable debounce time
 *
 * Example usage:
 *   RotaryEncoder encoder(10, 11, 12); // A, B, SW pins
 *   encoder.init();
 *   encoder.createEventQueue();
 *
 *   // In task loop:
 *   RotaryEvent event;
 *   if (xQueueReceive(encoder.getEventQueue(), &event, 0)) {
 *       switch (event.type) {
 *           case RotaryEventType::ButtonPress:
 *               // Handle button press
 *               break;
 *           case RotaryEventType::Clockwise:
 *               // Handle clockwise rotation
 *               break;
 *           case RotaryEventType::CounterClockwise:
 *               // Handle counter-clockwise rotation
 *               break;
 *       }
 *   }
 */
class RotaryEncoder {
public:
    /**
     * @brief Construct a new Rotary Encoder object.
     * @param pinA GPIO pin connected to rotary encoder A phase
     * @param pinB GPIO pin connected to rotary encoder B phase
     * @param pinSW GPIO pin connected to rotary encoder switch/button
     */
    RotaryEncoder(uint8_t pinA, uint8_t pinB, uint8_t pinSW);

    /**
     * @brief Initialize the rotary encoder hardware.
     *
     * Configures GPIO pins and sets up interrupts for rotation detection
     * and button press detection.
     */
    void init();

    /**
     * @brief Create a FreeRTOS queue for event handling.
     * @param queueLength Maximum number of events the queue can hold
     * @return true if queue creation succeeded, false otherwise
     */
    bool createEventQueue(UBaseType_t queueLength = 10);

    /**
     * @brief Get the event queue handle.
     * @return QueueHandle_t FreeRTOS queue handle for receiving events
     */
    QueueHandle_t getEventQueue() const { return eventQueue; }

    /**
     * @brief Set the debounce time for button presses.
     * @param debounceMs Debounce time in milliseconds
     */
    void setDebounceTime(uint32_t debounceMs);

private:
    uint8_t pinA;          ///< GPIO pin for rotary encoder A phase
    uint8_t pinB;          ///< GPIO pin for rotary encoder B phase
    uint8_t pinSW;         ///< GPIO pin for rotary encoder switch/button

    uint32_t debounceTimeMs; ///< Debounce time for button presses in milliseconds
    TickType_t lastButtonPress; ///< FreeRTOS tick count of last button press

    QueueHandle_t eventQueue; ///< FreeRTOS queue for passing events

    static RotaryEncoder* instance; ///< Static instance pointer for ISR access

    /**
     * @brief Static GPIO interrupt callback function.
     * @param gpio GPIO pin that triggered the interrupt
     * @param events Type of interrupt event
     *
     * This function is called from interrupt context when a GPIO event occurs.
     * It detects rotary encoder rotation and button presses, and adds events
     * to the queue for processing in task context.
     */
    static void gpioCallback(uint gpio, uint32_t events);
};

#endif // ROTARY_ENCODER_H